root = "."
tmp_dir = "tmp"
[build]
cmd = "./bin/templ generate && go build -o ./tmp/main ."
bin = "./tmp/main"
delay = 200
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "templ", "html", "django"]
exclude_regex = ["_test\\.go", "_templ\\.go"]
