[phases.install]
cmds = ["go install github.com/a-h/templ/cmd/templ@latest", "go get"]
[phases.pre_build]
cmds = ["./bin/templ generate"]
[phases.build]
cmds = ["go build -o ./out ./."]
[phases.pre_start]
cmds = ["./bin/dbmate up"]
