[phases.install]
cmds = ["go get"]
[phases.pre_build]
cmds = ["./bin/templ generate"]
[phases.build]
cmds = ["go build -o ./bin/bug-tracker ./."]
[phases.pre_start]
cmds = ["./bin/dbmate up"]
[start]
cmds = ["./bin/bug-tracker"]
