// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747

package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ProjectCreateView(template templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"p-10 max-w-screen-sm\"><a href=\"/app/project\" hx-boost=\"true\" hx-target-error=\"#project-creation-error\" hx-push-url=\"true\" class=\"text-blue-900 hover:underline\">&lt; Go back</a><form hx-ext=\"response-targets\" action=\"/app/project/create\" hx-post=\"/app/project/create\" hx-post=\"create\" hx-target-error=\"#project-creation-error\" method=\"post\"><h1 class=\"text-2xl\">Create Project</h1><div class=\"mb-2\"><label for=\"project-name-input\" class=\"block\">Project Name:</label> <input id=\"project-name-input\" class=\"w-full border border-gray-700 p-1 text-lg\" type=\"text\" name=\"name\"></div><div class=\"mb-2\"><label for=\"project-name-description\" class=\"block\">Project Description:</label> <textarea id=\"project-name-description\" class=\"w-full border border-gray-700 p-1 text-lg\" type=\"text\" name=\"description\"></textarea></div><button type=\"submit\" class=\"p-2 border border-black hover:bg-gray-200 duration-100\">Create new project</button></form><div class=\"text-red-600\" id=\"project-creation-error\"></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = template.Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
