// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ProjectID   string
	Name        string
	Description pgtype.Text
	CreatedBy   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SchemaMigration struct {
	Version string
}

type Ticket struct {
	TicketID         string
	Title            string
	Description      pgtype.Text
	Status           int16
	Priority         int16
	AssigneeID       pgtype.Text
	AssigneeUsername pgtype.Text
	AssigneeEmail    pgtype.Text
	CreatedBy        string
	ProjectID        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	UserID       string
	Username     string
	PasswordHash string
	Email        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserProject struct {
	UserID    string
	Role      string
	ProjectID string
}

type UserProjectInvitation struct {
	InvitationID string
	SenderID     pgtype.Text
	RecipientID  string
	ProjectID    string
	Role         string
	Status       int16
	CreatedAt    pgtype.Timestamptz
	ResolvedAt   pgtype.Timestamptz
}

type UserSession struct {
	K string
	V []byte
	E int64
}
